name: vital_signs_monitor
    description: A Flutter app for real-time vital signs monitoring.
    publish_to: 'none'
    version: 1.0.0+1

    environment:
      sdk: '>=3.0.0 <4.0.0'

    dependencies:
      flutter:
        sdk: flutter
      cupertino_icons: ^1.0.2
      fl_chart: ^0.63.0

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^2.0.0
